# File: D:/mstair-common/pyproject.toml

[build-system]
    build-backend = "setuptools.build_meta"
    requires      = ["setuptools>=65", "wheel"]


[project]
    authors = [{ name = "Morgan Stair" }]
    dependencies = [
        "boto3-stubs[apigateway,apigatewayv2,cloudformation,cloudfront,cognito-identity,cognito-idp,dynamodb,iam,iot,lambda,logs,s3,sts,ssm,stepfunctions,sts,wafv2]>=1.35.0",
        "boto3>=1.35.0",
        "botocore-stubs>=1.35.0",
        "botocore>=1.35.0",
        "charset_normalizer>=3.3.2",
        "click>=8.1.7",
        "colorama>=0.4.6",
        "diskcache>=5.6.1",
        "gitpython>=3.1.43",
        "json5",
        "mypy>=1.10.0",
        "nltk>=3.8.1",
        "pytest",
        "python-dotenv>=1.1.1",
        "pytz",
        "ruff",
        "types-awscrt>=0.21.0",
    ]
    description = "Common libraries for mstair projects"
    license = "MIT"
    name = "mstair-common"
    readme = "README.md"
    requires-python = ">=3.13"
    version = "0.1.1"


    [project.optional-dependencies]
        dev  = []
        test = []

[tool.build]
    build-base = ".cache/tool-build"

    [tool.build.python]
        local_packages = ["mstair"]
        local_src_dir  = "src"


[tool.pytest.ini_options]
    addopts = "-rNfExXp -q --maxfail=5"
    cache_dir = ".pytest_cache"
    console_output_style = "classic"
    markers = [
        "e2e: end-to-end tests simulating real user workflows",
        "functional: verifies individual features or behaviors",
        "integration: tests that verify interactions between components",
        "manual: requires human intervention or cannot be automated",
        "regression: ensures previously fixed bugs don't reappear",
        "slow: long-running or resource-intensive tests",
        "unit: fast, isolated tests with no external dependencies",
    ]
    minversion = "8.3"
    norecursedirs = "*.egg-info"
    testpaths = ["src/*/", "src/*/*/"]


[tool.setuptools.packages.find]
    include = ["mstair", "mstair.*"]
    where   = ["src"]


[tool.setuptools.package-data]
    "mstair"        = ["py.typed"]
    "mstair.common" = ["**/*.pyi", "*.pyi", "py.typed"]
