# File: ruff.toml
# This configuration file is for the Ruff linter (https://ruff.rs/).

fix = true
line-length = 101
respect-gitignore = true
src = ["src"]
target-version = "py313"
unsafe-fixes = false


exclude = [
    ".cache",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    ".venv*",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
]


[lint]
fixable = ["ALL"]
unfixable = ["F401", "F403", "TID252"]
select = ["B", "C4", "E", "F", "I", "PL", "RUF", "SIM", "TID", "UP"]
extend-select = ["I001", "I002"]
ignore = [
    "B007",
    "B009",
    "B010",
    "B017",
    "B028",
    "B904",
    "C408",
    "D100",
    "D101",
    "D104",
    "D105",
    "D107",
    "E501",
    "E731",
    "F403",
    "FA102",
    "PLR0913",
    "PLR2004",
    "PLW0603",
    "PLW2901",
    "RUF002",
    "RUF009",
    "RUF010",
    "RUF022",
    "RUF023",
    "RUF052",
    "SIM102",
    "SIM103",
    "SIM108",
    "SIM114",
    "SIM118",
    "TID252",
    "UP006",
    "UP014",
    "UP017",
    "UP028",
    "UP032",
    "UP037",
    "UP040",
]

[lint.pylint]
max-args = 8
max-returns = 9
max-branches = 15

[lint.isort]
detect-same-package = true
force-single-line = false
force-to-top = ["__future__"]
known-first-party = ["mstair"]
known-local-folder = ["src"]
lines-after-imports = 2
order-by-type = true

[lint.mccabe]
max-complexity = 8

[format]
indent-style = "space"
line-ending = "cr-lf"
quote-style = "double"
skip-magic-trailing-comma = false
