# File: ruff.toml
# This configuration file is for the Ruff linter (https://ruff.rs/).

exclude = [
    ".cache",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    ".venv*",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
]
fix = true
line-length = 101
respect-gitignore = true
src = [ "python", "scripts", "src", "tests", "tools" ]
target-version = "py313"
unsafe-fixes = false


[lint]
    extend-select = [ "I001", "I002" ]
    fixable = [ "ALL" ]
    ignore = [
        "B007",
        "B009",
        "B010",
        "B017",
        "B028",
        "B904",
        "C408",
        "D100",
        "D101",
        "D104",
        "D105",
        "D107",
        "E501",
        "E731",
        "F403",
        "FA102",
        "PLC1901",
        "PLR0904",
        "PLR0913",
        "PLR2004",
        "PLR6301",
        "PLW0603",
        "PLW2901",
        "RUF002",
        "RUF009",
        "RUF010",
        "RUF022",
        "RUF023",
        "RUF052",
        "SIM102",
        "SIM103",
        "SIM108",
        "SIM114",
        "SIM118",
        "TID252",
        "UP006",
        "UP014",
        "UP017",
        "UP028",
        "UP032",
        "UP037",
        "UP040",
    ]
    select = [ "B", "C4", "E", "F", "I", "PL", "RUF", "SIM", "TID", "UP" ]
    unfixable = [ "F401", "F403", "TID252" ]

    [lint.pylint]
        max-args           = 8
        max-branches       = 15
        max-public-methods = 30
        max-returns        = 9

    [lint.isort]
        detect-same-package = true
        force-single-line   = false
        force-to-top        = [ "__future__" ]
        known-first-party   = [ "autocomment", "pdf2rtf", "plib_", "tests" ]
        known-local-folder  = [ "src" ]
        lines-after-imports = 2
        order-by-type       = true

    [lint.mccabe]
        max-complexity = 8

[format]
    indent-style              = "space"
    quote-style               = "double"
    skip-magic-trailing-comma = false
