include = ["**/*.toml"]
exclude = ["**/.venv/**", "**/.cache/**", "**/node_modules/**"]

[formatting]
align_comments = true
align_entries = true
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true
column_width = 100
indent_string = "    "
inline_table_expand = true
reorder_arrays = true
reorder_inline_tables = true
reorder_keys = true
trailing_newline = true
