exclude = [
    "**/.cache/**",
    "**/.venv/**",
    "**/node_modules/**",
]
include = ["**/*.toml"]

[formatting]
    align_comments        = true
    align_entries         = true
    allowed_blank_lines   = 1
    array_auto_collapse   = true
    array_auto_expand     = true
    array_trailing_comma  = true
    column_width          = 40
    compact_entries       = false
    compact_inline_tables = false
    crlf                  = true
    indent_entries        = true
    indent_string         = "    "
    indent_tables         = false
    inline_table_expand   = true
    reorder_arrays        = true
    reorder_inline_tables = true
    reorder_keys          = true
    trailing_newline      = true
