# File: taplo.toml

exclude = [ "**/.cache/**", "**/.venv/**", "**/node_modules/**" ]
include = [ "**/*.toml" ]

[formatting]
    align_comments        = true
    align_entries         = true
    array_auto_collapse   = false
    array_auto_expand     = true
    array_trailing_comma  = true
    column_width          = 101
    crlf                  = true
    indent_entries        = true
    indent_string         = "    "
    indent_tables         = false
    inline_table_expand   = true
    reorder_arrays        = true
    reorder_inline_tables = true
    reorder_keys          = true
    trailing_newline      = true
