# This file is autogenerated; do not edit directly.
"""
mstair.common.xdumps public API.
"""

# <AUTOGEN_INIT>
from mstair.common.xdumps import (
    customizer_registry,
    model,
    test_xdumps,
    token_stream,
    view,
    xdumps_api,
)


__all__ = ["customizer_registry", "model", "test_xdumps", "token_stream", "view", "xdumps_api"]
# </AUTOGEN_INIT>
